<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYbtrtu1\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYbtrtu1/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYbtrtu1.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYbtrtu1\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYbtrtu1\appProdProjectContainer([
    'container.build_hash' => 'Ybtrtu1',
    'container.build_id' => 'd98a09e8',
    'container.build_time' => 1569818021,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYbtrtu1');
