<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYudcxzl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYudcxzl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYudcxzl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYudcxzl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYudcxzl\appProdProjectContainer([
    'container.build_hash' => 'Yudcxzl',
    'container.build_id' => 'dd2002ef',
    'container.build_time' => 1571123569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYudcxzl');
