<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxgxlxk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxgxlxk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKxgxlxk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKxgxlxk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKxgxlxk\appProdProjectContainer([
    'container.build_hash' => 'Kxgxlxk',
    'container.build_id' => 'f97e9470',
    'container.build_time' => 1570096982,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxgxlxk');
