<?php
/**
* 2007-2017 PrestaShop
*
* Jms Mega Menu module for prestashop
*
*  @author    Joommasters <joommasters@gmail.com>
*  @copyright 2007-2017 Joommasters
*  @license   license http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL
*  @Website: http://www.joommasters.com
*/

$query = "DROP TABLE IF EXISTS `_DB_PREFIX_jmsvermegamenu`;
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_jmsvermegamenu` (
  `mitem_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_shop` int(11) unsigned NOT NULL,
  `parent_id` int(10) unsigned NOT NULL,
  `type` varchar(30) NOT NULL,
  `value` varchar(255) NOT NULL,
  `html_content` text NOT NULL,
  `active` tinyint(1) NOT NULL,
  `target` varchar(25) NOT NULL,
  `params` text NOT NULL,
  `ordering` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`mitem_id`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=215 ;

INSERT INTO `_DB_PREFIX_jmsvermegamenu` (`mitem_id`, `id_shop`, `parent_id`, `type`, `value`, `html_content`, `active`, `target`, `params`, `ordering`) VALUES
(84, 1, 0, 'link', '', '', 1, '_self', '{\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"90\"},{\"item\":\"91\"},{\"item\":\"92\"},{\"item\":\"93\"},{\"item\":\"94\"},{\"item\":\"95\"},{\"item\":\"96\"},{\"item\":\"97\"}]}]]}}', 1),
(85, 1, 0, 'category', '40', '', 1, '_self', '{\"class\":\"must-see mega-fullwidth\",\"align\":\"center\",\"sub\":{\"fullwidth\":\"1\",\"width\":\"1170\",\"row\":[[{\"width\":\"3\",\"items\":[{\"item\":\"143\"},{\"item\":\"144\"},{\"item\":\"145\"},{\"item\":\"146\"},{\"item\":\"147\"},{\"item\":\"148\"},{\"item\":\"149\"},{\"item\":\"150\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"151\"},{\"item\":\"152\"},{\"item\":\"153\"},{\"item\":\"154\"},{\"item\":\"155\"},{\"item\":\"156\"},{\"item\":\"157\"},{\"item\":\"158\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"159\"},{\"item\":\"160\"},{\"item\":\"161\"},{\"item\":\"162\"},{\"item\":\"163\"},{\"item\":\"164\"},{\"item\":\"165\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"166\"},{\"item\":\"167\"},{\"item\":\"168\"},{\"item\":\"169\"},{\"item\":\"170\"},{\"item\":\"171\"},{\"item\":\"172\"},{\"item\":\"173\"},{\"item\":\"174\"},{\"item\":\"175\"},{\"item\":\"176\"},{\"item\":\"177\"},{\"item\":\"178\"}]}]]}}', 2),
(86, 1, 0, 'product', '', '', 1, '_self', '{\"class\":\"mega-fullwidth\",\"align\":\"center\",\"sub\":{\"fullwidth\":\"1\",\"width\":\"1480\",\"row\":[[{\"width\":\"3\",\"items\":[{\"item\":\"111\"},{\"item\":\"112\"},{\"item\":\"113\"},{\"item\":\"114\"},{\"item\":\"115\"},{\"item\":\"116\"},{\"item\":\"117\"},{\"item\":\"118\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"126\"},{\"item\":\"119\"},{\"item\":\"120\"},{\"item\":\"121\"},{\"item\":\"122\"},{\"item\":\"123\"},{\"item\":\"124\"},{\"item\":\"125\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"127\"},{\"item\":\"128\"},{\"item\":\"129\"},{\"item\":\"130\"},{\"item\":\"131\"},{\"item\":\"132\"},{\"item\":\"133\"},{\"item\":\"134\"}]},{\"width\":\"3\",\"items\":[{\"item\":\"135\"},{\"item\":\"136\"},{\"item\":\"137\"},{\"item\":\"138\"},{\"item\":\"139\"},{\"item\":\"140\"},{\"item\":\"141\"},{\"item\":\"142\"}]}]]}}', 3),
(87, 1, 0, 'product', '', '', 1, '_self', '{\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"98\"},{\"item\":\"99\"},{\"item\":\"100\"},{\"item\":\"101\"},{\"item\":\"102\"},{\"item\":\"103\"},{\"item\":\"104\"},{\"item\":\"105\"}]}]]}}', 4),
(88, 1, 0, 'jmsblog-singlepost', '13', '', 1, '_self', '{\"sub\":{\"row\":[[{\"width\":\"12\",\"items\":[{\"item\":\"179\"},{\"item\":\"180\"},{\"item\":\"181\"},{\"item\":\"182\"},{\"item\":\"183\"}]}]]}}', 5),
(89, 1, 0, 'link', 'index.php?controller=contact', '', 1, '_self', '{}', 6),
(90, 1, 84, 'link', '', '', 1, '_self', '{\"title\":\"1\"}', 1),
(91, 1, 84, 'link', 'index.php?settingpanel=1&jpb_homepage=6', '', 1, '_self', '{\"title\":\"1\"}', 2),
(92, 1, 84, 'link', 'index.php?settingpanel=1&jpb_homepage=7', '', 1, '_self', '{\"title\":\"1\"}', 3),
(93, 1, 84, 'link', 'index.php?settingpanel=1&jpb_homepage=8', '', 1, '_self', '{\"title\":\"1\"}', 4),
(94, 1, 84, 'link', 'index.php?settingpanel=1&jpb_homepage=9', '', 1, '_self', '{\"title\":\"1\"}', 5),
(95, 1, 84, 'link', 'index.php?settingpanel=1&jpb_homepage=10', '', 1, '_self', '{\"title\":\"1\"}', 6),
(96, 1, 84, 'link', 'index.php?settingpanel=1&jpb_homepage=11', '', 1, '_self', '{\"title\":\"1\"}', 7),
(97, 1, 84, 'link', 'index.php?settingpanel=1&jpb_homepage=12', '', 1, '_self', '{\"title\":\"1\"}', 8),
(98, 1, 87, 'cms', '16', '', 1, '_self', '{\"title\":\"1\"}', 1),
(99, 1, 87, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 2),
(100, 1, 87, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 3),
(101, 1, 87, 'link', 'index.php?controller=search&search_query=adiva', '', 1, '_self', '{\"title\":\"1\"}', 4),
(102, 1, 87, 'link', 'index.php?controller=products-comparison', '', 1, '_self', '{\"title\":\"1\"}', 5),
(103, 1, 87, 'cms', '1', '', 1, '_self', '{\"title\":\"1\"}', 6),
(104, 1, 87, 'cms', '1', '', 1, '_self', '{\"title\":\"1\"}', 7),
(105, 1, 87, 'link', 'index.php?controller=404', '', 1, '_self', '{\"title\":\"1\"}', 8),
(111, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms-adiva/assets/img/menu1.jpg\" alt=\"\" height=\"170\" width=\"320\" /></p>', 1, '_self', '{\"title\":\"0\"}', 0),
(112, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 1),
(113, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 2),
(114, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 3),
(115, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 4),
(116, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 5),
(117, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 6),
(118, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 7),
(119, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 9),
(120, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 10),
(121, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 11),
(122, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 12),
(123, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 13),
(124, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 14),
(125, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 15),
(126, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms-adiva/assets/img/menu2.jpg\" alt=\"\" height=\"170\" width=\"320\" /></p>', 1, '_self', '{\"title\":\"0\"}', 8),
(127, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms-adiva/assets/img/menu3.jpg\" alt=\"\" height=\"170\" width=\"320\" /></p>', 1, '_self', '{\"title\":\"0\"}', 16),
(128, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 17),
(129, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 18),
(130, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 19),
(131, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 20),
(132, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 21),
(133, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 22),
(134, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 23),
(135, 1, 86, 'html', 'html_content', '<p><img src=\"themes/jms-adiva/assets/img/menu4.jpg\" alt=\"\" height=\"170\" width=\"320\" /></p>', 1, '_self', '{\"title\":\"0\"}', 24),
(136, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 25),
(137, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 26),
(138, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 27),
(139, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 28),
(140, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 29),
(141, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 30),
(142, 1, 86, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 31),
(143, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 1),
(144, 1, 85, 'link', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left', '', 1, '_self', '{\"title\":\"1\"}', 2),
(145, 1, 85, 'link', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right', '', 1, '_self', '{\"title\":\"1\"}', 3),
(146, 1, 85, 'link', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no', '', 1, '_self', '{\"title\":\"1\"}', 4),
(147, 1, 85, 'link', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns', '', 1, '_self', '{\"title\":\"1\"}', 5),
(148, 1, 85, 'link', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery', '', 1, '_self', '{\"title\":\"1\"}', 6),
(149, 1, 85, 'link', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns', '', 1, '_self', '{\"title\":\"1\"}', 7),
(150, 1, 85, 'link', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns', '', 1, '_self', '{\"title\":\"1\"}', 8),
(151, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 9),
(152, 1, 85, 'product', '28', '', 1, '_self', '{\"title\":\"1\"}', 10),
(153, 1, 85, 'product', '14', '', 1, '_self', '{\"title\":\"1\"}', 11),
(154, 1, 85, 'product', '30', '', 1, '_self', '{\"title\":\"1\"}', 12),
(155, 1, 85, 'product', '31', '', 1, '_self', '{\"title\":\"1\"}', 13),
(156, 1, 85, 'product', '27', '', 1, '_self', '{\"title\":\"1\"}', 14),
(157, 1, 85, 'product', '26', '', 1, '_self', '{\"title\":\"1\"}', 15),
(158, 1, 85, 'product', '25', '', 1, '_self', '{\"title\":\"1\"}', 16),
(159, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 17),
(160, 1, 85, 'link', 'index.php?jpb_addtocart=default', '', 1, '_self', '{\"title\":\"1\"}', 18),
(161, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_popup', '', 1, '_self', '{\"title\":\"1\"}', 19),
(162, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_moveimage', '', 1, '_self', '{\"title\":\"1\"}', 20),
(163, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_cartbottom', '', 1, '_self', '{\"title\":\"1\"}', 21),
(164, 1, 85, 'link', 'index.php?jpb_addtocart=ajax_cartsidebar', '', 1, '_self', '{\"title\":\"1\"}', 22),
(165, 1, 85, 'link', 'index.php?jpb_addtocart=no_ajax', '', 1, '_self', '{\"title\":\"1\"}', 23),
(166, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\",\"group\":\"1\"}', 24),
(167, 1, 85, 'link', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left', '', 1, '_self', '{\"title\":\"1\"}', 25),
(168, 1, 85, 'link', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right', '', 1, '_self', '{\"title\":\"1\"}', 26),
(169, 1, 85, 'link', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no', '', 1, '_self', '{\"title\":\"1\"}', 27),
(170, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner', '', 1, '_self', '{\"title\":\"1\"}', 28),
(171, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc', '', 1, '_self', '{\"title\":\"1\"}', 29),
(172, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc', '', 1, '_self', '{\"title\":\"1\"}', 30),
(173, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2', '', 1, '_self', '{\"title\":\"1\"}', 31),
(174, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3', '', 1, '_self', '{\"title\":\"1\"}', 32),
(175, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4', '', 1, '_self', '{\"title\":\"1\"}', 33),
(176, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5', '', 1, '_self', '{\"title\":\"1\"}', 34),
(177, 1, 85, 'link', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6', '', 1, '_self', '{\"title\":\"1\"}', 35),
(178, 1, 85, 'link', '#', '', 1, '_self', '{\"title\":\"1\"}', 36),
(179, 1, 88, 'jmsblog-category', '1', '', 1, '_self', '{\"title\":\"1\"}', 1),
(180, 1, 88, 'jmsblog-singlepost', '13', '', 1, '_self', '{\"title\":\"1\"}', 2),
(181, 1, 88, 'jmsblog-categories', 'jmsblog_categories', '', 1, '_self', '{\"title\":\"1\"}', 3),
(182, 1, 88, 'jmsblog-tag', 'blog', '', 1, '_self', '{\"title\":\"1\"}', 4),
(183, 1, 88, 'jmsblog-archive', '2017-09', '', 1, '_self', '{\"title\":\"1\"}', 5),
(184, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left', '', 1, '_self', '', 1),
(185, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right', '', 1, '_self', '', 2),
(186, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no', '', 1, '_self', '', 3),
(187, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default', '', 1, '_self', '', 4),
(188, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns', '', 1, '_self', '', 5),
(189, 1, 179, 'link', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns', '', 1, '_self', '', 6),
(190, 1, 180, 'link', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left', '', 1, '_self', '', 1),
(191, 1, 180, 'link', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right', '', 1, '_self', '', 2),
(192, 1, 180, 'link', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no', '', 1, '_self', '', 3),
(193, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left', '', 1, '_self', '', 1),
(194, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right', '', 1, '_self', '', 2),
(195, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no', '', 1, '_self', '', 3),
(196, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left', '', 1, '_self', '', 4),
(197, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns', '', 1, '_self', '', 5),
(198, 1, 181, 'link', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns', '', 1, '_self', '', 6),
(199, 1, 0, 'link', '#', '', 1, '_self', '', 7),
(200, 1, 199, 'link', '', '', 1, '_self', '', 1),
(201, 1, 200, 'link', 'index.php?jpb_loadingstyle=1', '', 1, '_self', '', 1),
(202, 1, 200, 'link', 'index.php?jpb_loadingstyle=2', '', 1, '_self', '', 2),
(203, 1, 200, 'link', 'index.php?jpb_loadingstyle=3', '', 1, '_self', '', 3),
(204, 1, 200, 'link', 'index.php?jpb_loadingstyle=4', '', 1, '_self', '', 4),
(205, 1, 200, 'link', 'index.php?jpb_loadingstyle=5', '', 1, '_self', '', 5),
(206, 1, 200, 'link', 'index.php?jpb_loadingstyle=6', '', 1, '_self', '', 6),
(207, 1, 199, 'cms', '10', '', 1, '_self', '', 2),
(208, 1, 199, 'cms', '11', '', 1, '_self', '', 3),
(209, 1, 199, 'cms', '12', '', 1, '_self', '', 4),
(210, 1, 199, 'cms', '13', '', 1, '_self', '', 5),
(211, 1, 199, 'cms', '14', '', 1, '_self', '', 6),
(212, 1, 199, 'cms', '16', '', 1, '_self', '', 7),
(213, 1, 199, 'cms', '17', '', 1, '_self', '', 8),
(214, 1, 199, 'cms', '18', '', 1, '_self', '', 9);

DROP TABLE IF EXISTS `_DB_PREFIX_jmsvermegamenu_lang`;
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_jmsvermegamenu_lang` (
  `mitem_id` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `name` varchar(50) NOT NULL,
  `menulink` varchar(255) NOT NULL
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_jmsvermegamenu_lang` (`mitem_id`, `id_lang`, `name`, `menulink`) VALUES
(84, 1, 'Home', 'indexen.php'),
(85, 1, 'Shop', ''),
(86, 1, 'Products', ''),
(87, 1, 'Pages', ''),
(88, 1, 'Blog', ''),
(89, 1, 'Contact', 'index.php?controller=contact'),
(90, 1, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=1'),
(91, 1, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(92, 1, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(93, 1, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(94, 1, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(95, 1, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(96, 1, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(97, 1, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(98, 1, 'Typography', ''),
(99, 1, 'Inforgraphic', '#'),
(100, 1, 'Our Store', '#'),
(101, 1, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(102, 1, 'Compare page', 'index.php?controller=products-comparison'),
(103, 1, 'Offline Page', ''),
(104, 1, 'Our Office', ''),
(105, 1, '404 Page', 'index.php?controller=404'),
(111, 1, 'Women Image', ''),
(112, 1, 'Women', '#'),
(113, 1, 'Dresess', '#'),
(114, 1, 'Skinny', '#'),
(115, 1, 'High-Heels', '#'),
(116, 1, 'Jumpsuits', '#'),
(117, 1, 'Knitwear', '#'),
(118, 1, 'Gymwear', '#'),
(119, 1, 'Accessories', '#'),
(120, 1, 'Shoes & Bags', '#'),
(121, 1, 'Sunglasses', '#'),
(122, 1, 'Watches & Jewelry', '#'),
(123, 1, 'Scarves & Gloves', '#'),
(124, 1, 'Hats & Ties', '#'),
(125, 1, 'Belts', '#'),
(126, 1, 'Accessories Image', ''),
(127, 1, 'Men Image', ''),
(128, 1, 'Men', '#'),
(129, 1, 'Blazers', '#'),
(130, 1, 'Trousers', '#'),
(131, 1, 'T-Shirts', '#'),
(132, 1, 'Polo-Shirts', '#'),
(133, 1, 'Short', '#'),
(134, 1, 'Jeans', '#'),
(135, 1, 'Discount Image', ''),
(136, 1, 'DISCOUNT', '#'),
(137, 1, 'Polo-Shirts', '#'),
(138, 1, 'Jeans', '#'),
(139, 1, 'Dresess', '#'),
(140, 1, 'Shorts', '#'),
(141, 1, 'Trousers', '#'),
(142, 1, 'Sweatshirts', '#'),
(85, 2, 'Shop', ''),
(85, 3, 'Shop', ''),
(85, 5, 'Shop', ''),
(85, 8, 'Shop', ''),
(89, 2, 'Contact', 'index.php?controller=contact'),
(89, 3, 'Contact', 'index.php?controller=contact'),
(89, 5, 'Contact', 'index.php?controller=contact'),
(89, 8, 'Contact', 'index.php?controller=contact'),
(98, 2, 'Typography', ''),
(98, 3, 'Typography', ''),
(98, 5, 'Typography', ''),
(98, 8, 'Typography', ''),
(105, 2, '404 Page', 'index.php?controller=404'),
(105, 3, '404 Page', 'index.php?controller=404'),
(105, 5, '404 Page', 'index.php?controller=404'),
(105, 8, '404 Page', 'index.php?controller=404'),
(101, 2, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(101, 3, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(101, 5, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(101, 8, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(102, 2, 'Compare page', 'index.php?controller=products-comparison'),
(102, 3, 'Compare page', 'index.php?controller=products-comparison'),
(102, 5, 'Compare page', 'index.php?controller=products-comparison'),
(102, 8, 'Compare page', 'index.php?controller=products-comparison'),
(90, 2, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(90, 3, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(90, 5, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(90, 8, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 2, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 3, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 5, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 8, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(92, 2, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(92, 3, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(92, 5, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(92, 8, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(93, 2, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(93, 3, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(93, 5, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(93, 8, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(94, 2, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(94, 3, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(94, 5, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(94, 8, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(95, 2, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(95, 3, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(95, 5, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(95, 8, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(96, 2, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(96, 3, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(96, 5, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(96, 8, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(97, 2, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(97, 3, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(97, 5, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(97, 8, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(111, 2, 'Women Image', ''),
(111, 3, 'Women Image', ''),
(111, 5, 'Women Image', ''),
(111, 8, 'Women Image', ''),
(126, 2, 'Accessories Image', ''),
(126, 3, 'Accessories Image', ''),
(126, 5, 'Accessories Image', ''),
(126, 8, 'Accessories Image', ''),
(127, 2, 'Men Image', ''),
(127, 3, 'Men Image', ''),
(127, 5, 'Men Image', ''),
(127, 8, 'Men Image', ''),
(135, 2, 'Discount Image', ''),
(135, 3, 'Discount Image', ''),
(135, 5, 'Discount Image', ''),
(135, 8, 'Discount Image', ''),
(111, 4, 'Women Image', ''),
(111, 6, 'Women Image', ''),
(111, 7, 'Women Image', ''),
(126, 4, 'Accessories Image', ''),
(126, 6, 'Accessories Image', ''),
(126, 7, 'Accessories Image', ''),
(127, 4, 'Men Image', ''),
(127, 6, 'Men Image', ''),
(127, 7, 'Men Image', ''),
(135, 4, 'Discount Image', ''),
(135, 6, 'Discount Image', ''),
(135, 7, 'Discount Image', ''),
(85, 4, 'Shop', ''),
(85, 6, 'Shop', ''),
(85, 7, 'Shop', ''),
(88, 2, 'Blog', ''),
(88, 3, 'Blog', ''),
(88, 4, 'Blog', ''),
(88, 5, 'Blog', ''),
(88, 6, 'Blog', ''),
(88, 7, 'Blog', ''),
(88, 8, 'Blog', ''),
(143, 1, 'Product Layout', '#'),
(143, 2, 'Product Layout', '#'),
(143, 3, 'Product Layout', '#'),
(143, 4, 'Product Layout', '#'),
(143, 5, 'Product Layout', '#'),
(143, 6, 'Product Layout', '#'),
(143, 7, 'Product Layout', '#'),
(143, 8, 'Product Layout', '#'),
(144, 1, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 2, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 3, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 4, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 5, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 6, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 7, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(144, 8, 'Left sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=left'),
(145, 1, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 2, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 3, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 4, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 5, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 6, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 7, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(145, 8, 'Right sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=right'),
(146, 1, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 2, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 3, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 4, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 5, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 6, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 7, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(146, 8, 'No Sidebar', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no'),
(147, 1, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 2, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 3, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 4, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 5, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 6, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 7, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(147, 8, '3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-3columns'),
(148, 1, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 2, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 3, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 4, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 5, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 6, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 7, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(148, 8, 'Gallery Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-gallery'),
(149, 1, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(149, 2, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(149, 3, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(149, 4, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(149, 5, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(149, 6, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(149, 7, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(149, 8, 'Sticky 2 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-2columns'),
(150, 1, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(150, 2, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(150, 3, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(150, 4, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(150, 5, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(150, 6, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(150, 7, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(150, 8, 'Sticky 3 Columns Layout', 'index.php?id_product=14&id_product_attribute=206&rewrite=isherwood-button-down-collar-cotton&controller=product&id_lang=1&sidebar=no&layout=product-layout-sticky-3columns'),
(151, 1, 'Product Type', '#'),
(151, 2, 'Product Type', '#'),
(151, 3, 'Product Type', '#'),
(151, 4, 'Product Type', '#'),
(151, 5, 'Product Type', '#'),
(151, 6, 'Product Type', '#'),
(151, 7, 'Product Type', '#'),
(151, 8, 'Product Type', '#'),
(152, 1, 'Virtual Product', ''),
(152, 2, 'Virtual Product', ''),
(152, 3, 'Virtual Product', ''),
(152, 4, 'Virtual Product', ''),
(152, 5, 'Virtual Product', ''),
(152, 6, 'Virtual Product', ''),
(152, 7, 'Virtual Product', ''),
(152, 8, 'Virtual Product', ''),
(153, 1, 'Standard Product', ''),
(153, 2, 'Standard Product', ''),
(153, 3, 'Standard Product', ''),
(153, 4, 'Standard Product', ''),
(153, 5, 'Standard Product', ''),
(153, 6, 'Standard Product', ''),
(153, 7, 'Standard Product', ''),
(153, 8, 'Standard Product', ''),
(154, 1, 'Pack Products', ''),
(154, 2, 'Pack Products', ''),
(154, 3, 'Pack Products', ''),
(154, 4, 'Pack Products', ''),
(154, 5, 'Pack Products', ''),
(154, 6, 'Pack Products', ''),
(154, 7, 'Pack Products', ''),
(154, 8, 'Pack Products', ''),
(155, 1, 'Product Color Swatch', ''),
(155, 2, 'Product Color Swatch', ''),
(155, 3, 'Product Color Swatch', ''),
(155, 4, 'Product Color Swatch', ''),
(155, 5, 'Product Color Swatch', ''),
(155, 6, 'Product Color Swatch', ''),
(155, 7, 'Product Color Swatch', ''),
(155, 8, 'Product Color Swatch', ''),
(156, 1, 'Product with custom tab', ''),
(156, 2, 'Product with custom tab', ''),
(156, 3, 'Product with custom tab', ''),
(156, 4, 'Product with custom tab', ''),
(156, 5, 'Product with custom tab', ''),
(156, 6, 'Product with custom tab', ''),
(156, 7, 'Product with custom tab', ''),
(156, 8, 'Product with custom tab', ''),
(157, 1, 'Product with video', ''),
(157, 2, 'Product with video', ''),
(157, 3, 'Product with video', ''),
(157, 4, 'Product with video', ''),
(157, 5, 'Product with video', ''),
(157, 6, 'Product with video', ''),
(157, 7, 'Product with video', ''),
(157, 8, 'Product with video', ''),
(158, 1, 'Product out of stock', ''),
(158, 2, 'Product out of stock', ''),
(158, 3, 'Product out of stock', ''),
(158, 4, 'Product out of stock', ''),
(158, 5, 'Product out of stock', ''),
(158, 6, 'Product out of stock', ''),
(158, 7, 'Product out of stock', ''),
(158, 8, 'Product out of stock', ''),
(159, 1, 'Add to cart', '#'),
(159, 2, 'Add to cart', '#'),
(159, 3, 'Add to cart', '#'),
(159, 4, 'Add to cart', '#'),
(159, 5, 'Add to cart', '#'),
(159, 6, 'Add to cart', '#'),
(159, 7, 'Add to cart', '#'),
(159, 8, 'Add to cart', '#'),
(160, 1, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 2, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 3, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 4, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 5, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 6, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 7, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(160, 8, 'Ajax Default', 'index.php?jpb_addtocart=default'),
(161, 1, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 2, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 3, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 4, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 5, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 6, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 7, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(161, 8, 'Ajax + Preview Popup', 'index.php?jpb_addtocart=ajax_popup'),
(162, 1, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 2, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 3, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 4, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 5, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 6, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 7, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(162, 8, 'Ajax + Image Moving', 'index.php?jpb_addtocart=ajax_moveimage'),
(163, 1, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 2, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 3, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 4, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 5, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 6, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 7, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(163, 8, 'Ajax + Cart at Bottom', 'index.php?jpb_addtocart=ajax_cartbottom'),
(164, 1, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 2, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 3, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 4, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 5, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 6, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 7, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(164, 8, 'Ajax + Cart at Sidebar', 'index.php?jpb_addtocart=ajax_cartsidebar'),
(165, 1, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 2, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 3, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 4, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 5, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 6, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 7, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(165, 8, 'No Ajax', 'index.php?jpb_addtocart=no_ajax'),
(166, 1, 'Category Layout', '#'),
(166, 2, 'Category Layout', '#'),
(166, 3, 'Category Layout', '#'),
(166, 4, 'Category Layout', '#'),
(166, 5, 'Category Layout', '#'),
(166, 6, 'Category Layout', '#'),
(166, 7, 'Category Layout', '#'),
(166, 8, 'Category Layout', '#'),
(167, 1, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 2, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 3, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 4, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 5, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 6, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 7, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(167, 8, 'Left sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=left'),
(168, 1, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 2, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 3, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 4, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 5, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 6, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 7, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(168, 8, 'Right sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=right'),
(169, 1, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 2, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 3, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 4, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 5, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 6, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 7, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(169, 8, 'No Sidebar', 'index.php?id_category=40&controller=category&id_lang=1&sidebar=no'),
(170, 1, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 2, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 3, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 4, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 5, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 6, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 7, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(170, 8, 'Category Banner', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-banner'),
(171, 1, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 2, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 3, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 4, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 5, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 6, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 7, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(171, 8, 'Sub Categories', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-bannerandesc'),
(172, 1, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 2, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 3, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 4, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 5, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 6, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 7, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(172, 8, 'Category Descriptions', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=left&layout=category-layout-desc'),
(173, 1, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 2, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 3, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 4, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 5, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 6, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 7, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(173, 8, 'Grid 2 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=2'),
(174, 1, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 2, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 3, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 4, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 5, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 6, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 7, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(174, 8, 'Grid 3 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=3'),
(175, 1, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 2, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 3, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 4, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 5, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 6, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 7, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(175, 8, 'Grid 4 Colums', 'index.php?id_category=46&controller=category&id_lang=1&ppr=4'),
(176, 1, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 2, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 3, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 4, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 5, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 6, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 7, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(176, 8, 'Grid 5 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=5'),
(177, 1, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 2, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 3, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 4, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 5, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 6, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 7, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(177, 8, 'Grid 6 Colums', 'index.php?id_category=46&controller=category&id_lang=1&sidebar=no&ppr=6'),
(178, 1, 'List Layout', '#'),
(178, 2, 'List Layout', '#'),
(178, 3, 'List Layout', '#'),
(178, 4, 'List Layout', '#'),
(178, 5, 'List Layout', '#'),
(178, 6, 'List Layout', '#'),
(178, 7, 'List Layout', '#'),
(178, 8, 'List Layout', '#'),
(179, 1, 'Blog Category', ''),
(179, 2, 'Blog Category', ''),
(179, 3, 'Blog Category', ''),
(179, 4, 'Blog Category', ''),
(179, 5, 'Blog Category', ''),
(179, 6, 'Blog Category', ''),
(179, 7, 'Blog Category', ''),
(179, 8, 'Blog Category', ''),
(180, 1, 'Blog single post', ''),
(180, 2, 'Blog single post', ''),
(180, 3, 'Blog single post', ''),
(180, 4, 'Blog single post', ''),
(180, 5, 'Blog single post', ''),
(180, 6, 'Blog single post', ''),
(180, 7, 'Blog single post', ''),
(180, 8, 'Blog single post', ''),
(181, 1, 'Blog categories', ''),
(181, 2, 'Blog categories', ''),
(181, 3, 'Blog categories', ''),
(181, 4, 'Blog categories', ''),
(181, 5, 'Blog categories', ''),
(181, 6, 'Blog categories', ''),
(181, 7, 'Blog categories', ''),
(181, 8, 'Blog categories', ''),
(182, 1, 'Blog Tags', ''),
(182, 2, 'Blog Tags', ''),
(182, 3, 'Blog Tags', ''),
(182, 4, 'Blog Tags', ''),
(182, 5, 'Blog Tags', ''),
(182, 6, 'Blog Tags', ''),
(182, 7, 'Blog Tags', ''),
(182, 8, 'Blog Tags', ''),
(183, 1, 'Blog Archives', ''),
(183, 2, 'Blog Archives', ''),
(183, 3, 'Blog Archives', ''),
(183, 4, 'Blog Archives', ''),
(183, 5, 'Blog Archives', ''),
(183, 6, 'Blog Archives', ''),
(183, 7, 'Blog Archives', ''),
(183, 8, 'Blog Archives', ''),
(184, 1, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 2, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 3, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 4, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 5, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 6, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 7, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(184, 8, 'Category - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=left'),
(185, 1, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 2, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 3, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 4, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 5, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 6, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 7, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(185, 8, 'Category - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=right'),
(186, 1, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 2, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 3, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 4, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 5, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 6, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 7, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(186, 8, 'Category - No sidebar', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no'),
(187, 1, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 2, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 3, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 4, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 5, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 6, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 7, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(187, 8, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-default'),
(188, 1, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 2, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 3, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 4, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 5, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 6, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 7, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(188, 8, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-3columns'),
(189, 1, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 2, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 3, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 4, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 5, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 6, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 7, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(189, 8, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=category&category_id=1&sidebar=no&layout=category-layout-4columns'),
(190, 1, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 2, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 3, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 4, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 5, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 6, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 7, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(190, 8, 'Left sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=left'),
(191, 1, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 2, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 3, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 4, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 5, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 6, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 7, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(191, 8, 'Right sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=right'),
(192, 1, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 2, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 3, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 4, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 5, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 6, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 7, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(192, 8, 'No Sidebar', 'index.php?fc=module&module=jmsblog&category_slug=news&post_id=13&controller=post&id_lang=1&sidebar=no'),
(193, 1, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 2, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 3, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 4, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 5, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 6, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 7, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(193, 8, 'Categories - Left sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(194, 1, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 2, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 3, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 4, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 5, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 6, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 7, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(194, 8, 'Categories - Right sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=right'),
(195, 1, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 2, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 3, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 4, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 5, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 6, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 7, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(195, 8, 'Categories - No sidebar', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no'),
(196, 1, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 2, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 3, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 4, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 5, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 6, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 7, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(196, 8, '2 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=left'),
(197, 1, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 2, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 3, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 4, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 5, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 6, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 7, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(197, 8, '3 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-3columns'),
(198, 1, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 2, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 3, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 4, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 5, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 6, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 7, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(198, 8, '4 Columns', 'index.php?fc=module&module=jmsblog&controller=categories&sidebar=no&layout=categories-layout-4columns'),
(199, 1, 'Elements', '#'),
(199, 2, 'Elements', '#'),
(199, 3, 'Elements', '#'),
(199, 4, 'Elements', '#'),
(199, 5, 'Elements', '#'),
(199, 6, 'Elements', '#'),
(199, 7, 'Elements', '#'),
(199, 8, 'Elements', '#'),
(200, 1, 'Loading Style', '#'),
(200, 2, 'Loading Style', '#'),
(200, 3, 'Loading Style', '#'),
(200, 4, 'Loading Style', '#'),
(200, 5, 'Loading Style', '#'),
(200, 6, 'Loading Style', '#'),
(200, 7, 'Loading Style', '#'),
(200, 8, 'Loading Style', '#'),
(201, 1, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(201, 2, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(201, 3, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(201, 4, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(201, 5, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(201, 6, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(201, 7, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(201, 8, 'Loading Style 1', 'index.php?jpb_loadingstyle=1'),
(202, 1, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(202, 2, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(202, 3, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(202, 4, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(202, 5, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(202, 6, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(202, 7, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(202, 8, 'Loading Style 2', 'index.php?jpb_loadingstyle=2'),
(203, 1, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(203, 2, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(203, 3, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(203, 4, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(203, 5, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(203, 6, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(203, 7, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(203, 8, 'Loading Style 3', 'index.php?jpb_loadingstyle=3'),
(204, 1, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(204, 2, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(204, 3, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(204, 4, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(204, 5, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(204, 6, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(204, 7, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(204, 8, 'Loading Style 4', 'index.php?jpb_loadingstyle=4'),
(205, 1, 'Loading Style 5', 'index.php?jpb_loadingstyle=5');
INSERT INTO `_DB_PREFIX_jmsvermegamenu_lang` (`mitem_id`, `id_lang`, `name`, `menulink`) VALUES
(205, 2, 'Loading Style 5', 'index.php?jpb_loadingstyle=5'),
(205, 3, 'Loading Style 5', 'index.php?jpb_loadingstyle=5'),
(205, 4, 'Loading Style 5', 'index.php?jpb_loadingstyle=5'),
(205, 5, 'Loading Style 5', 'index.php?jpb_loadingstyle=5'),
(205, 6, 'Loading Style 5', 'index.php?jpb_loadingstyle=5'),
(205, 7, 'Loading Style 5', 'index.php?jpb_loadingstyle=5'),
(205, 8, 'Loading Style 5', 'index.php?jpb_loadingstyle=5'),
(206, 1, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(206, 2, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(206, 3, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(206, 4, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(206, 5, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(206, 6, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(206, 7, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(206, 8, 'Loading Style 6', 'index.php?jpb_loadingstyle=6'),
(207, 1, 'Icon with text', ''),
(207, 2, 'Icon with text', ''),
(207, 3, 'Icon with text', ''),
(207, 4, 'Icon with text', ''),
(207, 5, 'Icon with text', ''),
(207, 6, 'Icon with text', ''),
(207, 7, 'Icon with text', ''),
(207, 8, 'Icon with text', ''),
(208, 1, 'Tabs', ''),
(208, 2, 'Tabs', ''),
(208, 3, 'Tabs', ''),
(208, 4, 'Tabs', ''),
(208, 5, 'Tabs', ''),
(208, 6, 'Tabs', ''),
(208, 7, 'Tabs', ''),
(208, 8, 'Tabs', ''),
(209, 1, 'Accordions', ''),
(209, 2, 'Accordions', ''),
(209, 3, 'Accordions', ''),
(209, 4, 'Accordions', ''),
(209, 5, 'Accordions', ''),
(209, 6, 'Accordions', ''),
(209, 7, 'Accordions', ''),
(209, 8, 'Accordions', ''),
(210, 1, 'Teams', ''),
(210, 2, 'Teams', ''),
(210, 3, 'Teams', ''),
(210, 4, 'Teams', ''),
(210, 5, 'Teams', ''),
(210, 6, 'Teams', ''),
(210, 7, 'Teams', ''),
(210, 8, 'Teams', ''),
(211, 1, 'Text with image', ''),
(211, 2, 'Text with image', ''),
(211, 3, 'Text with image', ''),
(211, 4, 'Text with image', ''),
(211, 5, 'Text with image', ''),
(211, 6, 'Text with image', ''),
(211, 7, 'Text with image', ''),
(211, 8, 'Text with image', ''),
(212, 1, 'Responsive Grid System', ''),
(212, 2, 'Responsive Grid System', ''),
(212, 3, 'Responsive Grid System', ''),
(212, 4, 'Responsive Grid System', ''),
(212, 5, 'Responsive Grid System', ''),
(212, 6, 'Responsive Grid System', ''),
(212, 7, 'Responsive Grid System', ''),
(212, 8, 'Responsive Grid System', ''),
(213, 1, 'Separators/Dividers', ''),
(213, 2, 'Separators/Dividers', ''),
(213, 3, 'Separators/Dividers', ''),
(213, 4, 'Separators/Dividers', ''),
(213, 5, 'Separators/Dividers', ''),
(213, 6, 'Separators/Dividers', ''),
(213, 7, 'Separators/Dividers', ''),
(213, 8, 'Separators/Dividers', ''),
(214, 1, 'Google map', ''),
(214, 2, 'Google map', ''),
(214, 3, 'Google map', ''),
(214, 4, 'Google map', ''),
(214, 5, 'Google map', ''),
(214, 6, 'Google map', ''),
(214, 7, 'Google map', ''),
(214, 8, 'Google map', ''),
(84, 2, 'Home', 'indexfr.php'),
(84, 3, 'Home', 'index.php'),
(84, 4, 'Home', 'index.php'),
(84, 5, 'Home', 'index.php'),
(84, 6, 'Home', 'index.php'),
(84, 7, 'Home', 'index.php'),
(84, 8, 'Home', 'index.php'),
(89, 4, 'Contact', 'index.php?controller=contact'),
(89, 6, 'Contact', 'index.php?controller=contact'),
(89, 7, 'Contact', 'index.php?controller=contact'),
(90, 4, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(90, 6, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(90, 7, 'Home 1', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 4, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 6, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(91, 7, 'Home 2', 'index.php?settingpanel=1&jpb_homepage=6'),
(92, 4, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(92, 6, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(92, 7, 'Home 3', 'index.php?settingpanel=1&jpb_homepage=7'),
(93, 4, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(93, 6, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(93, 7, 'Home 4', 'index.php?settingpanel=1&jpb_homepage=8'),
(94, 4, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(94, 6, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(94, 7, 'Home 5', 'index.php?settingpanel=1&jpb_homepage=9'),
(95, 4, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(95, 6, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(95, 7, 'Home 6', 'index.php?settingpanel=1&jpb_homepage=10'),
(96, 4, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(96, 6, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(96, 7, 'Home 7', 'index.php?settingpanel=1&jpb_homepage=11'),
(97, 4, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(97, 6, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(97, 7, 'Home 8', 'index.php?settingpanel=1&jpb_homepage=12'),
(99, 2, 'Inforgraphic', '#'),
(99, 3, 'Inforgraphic', '#'),
(99, 4, 'Inforgraphic', '#'),
(99, 5, 'Inforgraphic', '#'),
(99, 6, 'Inforgraphic', '#'),
(99, 7, 'Inforgraphic', '#'),
(99, 8, 'Inforgraphic', '#'),
(100, 2, 'Our Store', '#'),
(100, 3, 'Our Store', '#'),
(100, 4, 'Our Store', '#'),
(100, 5, 'Our Store', '#'),
(100, 6, 'Our Store', '#'),
(100, 7, 'Our Store', '#'),
(100, 8, 'Our Store', '#'),
(101, 4, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(101, 6, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(101, 7, 'Search Page', 'index.php?controller=search&search_query=adiva'),
(102, 4, 'Compare page', 'index.php?controller=products-comparison'),
(102, 6, 'Compare page', 'index.php?controller=products-comparison'),
(102, 7, 'Compare page', 'index.php?controller=products-comparison'),
(105, 4, '404 Page', 'index.php?controller=404'),
(105, 6, '404 Page', 'index.php?controller=404'),
(105, 7, '404 Page', 'index.php?controller=404'),
(112, 2, 'Women', '#'),
(112, 3, 'Women', '#'),
(112, 4, 'Women', '#'),
(112, 5, 'Women', '#'),
(112, 6, 'Women', '#'),
(112, 7, 'Women', '#'),
(112, 8, 'Women', '#'),
(113, 2, 'Dresess', '#'),
(113, 3, 'Dresess', '#'),
(113, 4, 'Dresess', '#'),
(113, 5, 'Dresess', '#'),
(113, 6, 'Dresess', '#'),
(113, 7, 'Dresess', '#'),
(113, 8, 'Dresess', '#'),
(114, 2, 'Skinny', '#'),
(114, 3, 'Skinny', '#'),
(114, 4, 'Skinny', '#'),
(114, 5, 'Skinny', '#'),
(114, 6, 'Skinny', '#'),
(114, 7, 'Skinny', '#'),
(114, 8, 'Skinny', '#'),
(115, 2, 'High-Heels', '#'),
(115, 3, 'High-Heels', '#'),
(115, 4, 'High-Heels', '#'),
(115, 5, 'High-Heels', '#'),
(115, 6, 'High-Heels', '#'),
(115, 7, 'High-Heels', '#'),
(115, 8, 'High-Heels', '#'),
(116, 2, 'Jumpsuits', '#'),
(116, 3, 'Jumpsuits', '#'),
(116, 4, 'Jumpsuits', '#'),
(116, 5, 'Jumpsuits', '#'),
(116, 6, 'Jumpsuits', '#'),
(116, 7, 'Jumpsuits', '#'),
(116, 8, 'Jumpsuits', '#'),
(117, 2, 'Knitwear', '#'),
(117, 3, 'Knitwear', '#'),
(117, 4, 'Knitwear', '#'),
(117, 5, 'Knitwear', '#'),
(117, 6, 'Knitwear', '#'),
(117, 7, 'Knitwear', '#'),
(117, 8, 'Knitwear', '#'),
(118, 2, 'Gymwear', '#'),
(118, 3, 'Gymwear', '#'),
(118, 4, 'Gymwear', '#'),
(118, 5, 'Gymwear', '#'),
(118, 6, 'Gymwear', '#'),
(118, 7, 'Gymwear', '#'),
(118, 8, 'Gymwear', '#'),
(119, 2, 'Accessories', '#'),
(119, 3, 'Accessories', '#'),
(119, 4, 'Accessories', '#'),
(119, 5, 'Accessories', '#'),
(119, 6, 'Accessories', '#'),
(119, 7, 'Accessories', '#'),
(119, 8, 'Accessories', '#'),
(120, 2, 'Shoes & Bags', '#'),
(120, 3, 'Shoes & Bags', '#'),
(120, 4, 'Shoes & Bags', '#'),
(120, 5, 'Shoes & Bags', '#'),
(120, 6, 'Shoes & Bags', '#'),
(120, 7, 'Shoes & Bags', '#'),
(120, 8, 'Shoes & Bags', '#'),
(121, 2, 'Sunglasses', '#'),
(121, 3, 'Sunglasses', '#'),
(121, 4, 'Sunglasses', '#'),
(121, 5, 'Sunglasses', '#'),
(121, 6, 'Sunglasses', '#'),
(121, 7, 'Sunglasses', '#'),
(121, 8, 'Sunglasses', '#'),
(122, 2, 'Watches & Jewelry', '#'),
(122, 3, 'Watches & Jewelry', '#'),
(122, 4, 'Watches & Jewelry', '#'),
(122, 5, 'Watches & Jewelry', '#'),
(122, 6, 'Watches & Jewelry', '#'),
(122, 7, 'Watches & Jewelry', '#'),
(122, 8, 'Watches & Jewelry', '#'),
(123, 2, 'Scarves & Gloves', '#'),
(123, 3, 'Scarves & Gloves', '#'),
(123, 4, 'Scarves & Gloves', '#'),
(123, 5, 'Scarves & Gloves', '#'),
(123, 6, 'Scarves & Gloves', '#'),
(123, 7, 'Scarves & Gloves', '#'),
(123, 8, 'Scarves & Gloves', '#'),
(124, 2, 'Hats & Ties', '#'),
(124, 3, 'Hats & Ties', '#'),
(124, 4, 'Hats & Ties', '#'),
(124, 5, 'Hats & Ties', '#'),
(124, 6, 'Hats & Ties', '#'),
(124, 7, 'Hats & Ties', '#'),
(124, 8, 'Hats & Ties', '#'),
(125, 2, 'Belts', '#'),
(125, 3, 'Belts', '#'),
(125, 4, 'Belts', '#'),
(125, 5, 'Belts', '#'),
(125, 6, 'Belts', '#'),
(125, 7, 'Belts', '#'),
(125, 8, 'Belts', '#'),
(128, 2, 'Men', '#'),
(128, 3, 'Men', '#'),
(128, 4, 'Men', '#'),
(128, 5, 'Men', '#'),
(128, 6, 'Men', '#'),
(128, 7, 'Men', '#'),
(128, 8, 'Men', '#'),
(129, 2, 'Blazers', '#'),
(129, 3, 'Blazers', '#'),
(129, 4, 'Blazers', '#'),
(129, 5, 'Blazers', '#'),
(129, 6, 'Blazers', '#'),
(129, 7, 'Blazers', '#'),
(129, 8, 'Blazers', '#'),
(130, 2, 'Trousers', '#'),
(130, 3, 'Trousers', '#'),
(130, 4, 'Trousers', '#'),
(130, 5, 'Trousers', '#'),
(130, 6, 'Trousers', '#'),
(130, 7, 'Trousers', '#'),
(130, 8, 'Trousers', '#'),
(131, 2, 'T-Shirts', '#'),
(131, 3, 'T-Shirts', '#'),
(131, 4, 'T-Shirts', '#'),
(131, 5, 'T-Shirts', '#'),
(131, 6, 'T-Shirts', '#'),
(131, 7, 'T-Shirts', '#'),
(131, 8, 'T-Shirts', '#'),
(132, 2, 'Polo-Shirts', '#'),
(132, 3, 'Polo-Shirts', '#'),
(132, 4, 'Polo-Shirts', '#'),
(132, 5, 'Polo-Shirts', '#'),
(132, 6, 'Polo-Shirts', '#'),
(132, 7, 'Polo-Shirts', '#'),
(132, 8, 'Polo-Shirts', '#'),
(133, 2, 'Short', '#'),
(133, 3, 'Short', '#'),
(133, 4, 'Short', '#'),
(133, 5, 'Short', '#'),
(133, 6, 'Short', '#'),
(133, 7, 'Short', '#'),
(133, 8, 'Short', '#'),
(134, 2, 'Jeans', '#'),
(134, 3, 'Jeans', '#'),
(134, 4, 'Jeans', '#'),
(134, 5, 'Jeans', '#'),
(134, 6, 'Jeans', '#'),
(134, 7, 'Jeans', '#'),
(134, 8, 'Jeans', '#'),
(136, 2, 'DISCOUNT', '#'),
(136, 3, 'DISCOUNT', '#'),
(136, 4, 'DISCOUNT', '#'),
(136, 5, 'DISCOUNT', '#'),
(136, 6, 'DISCOUNT', '#'),
(136, 7, 'DISCOUNT', '#'),
(136, 8, 'DISCOUNT', '#'),
(137, 2, 'Polo-Shirts', '#'),
(137, 3, 'Polo-Shirts', '#'),
(137, 4, 'Polo-Shirts', '#'),
(137, 5, 'Polo-Shirts', '#'),
(137, 6, 'Polo-Shirts', '#'),
(137, 7, 'Polo-Shirts', '#'),
(137, 8, 'Polo-Shirts', '#'),
(138, 2, 'Jeans', '#'),
(138, 3, 'Jeans', '#'),
(138, 4, 'Jeans', '#'),
(138, 5, 'Jeans', '#'),
(138, 6, 'Jeans', '#'),
(138, 7, 'Jeans', '#'),
(138, 8, 'Jeans', '#'),
(139, 2, 'Dresess', '#'),
(139, 3, 'Dresess', '#'),
(139, 4, 'Dresess', '#'),
(139, 5, 'Dresess', '#'),
(139, 6, 'Dresess', '#'),
(139, 7, 'Dresess', '#'),
(139, 8, 'Dresess', '#'),
(140, 2, 'Shorts', '#'),
(140, 3, 'Shorts', '#'),
(140, 4, 'Shorts', '#'),
(140, 5, 'Shorts', '#'),
(140, 6, 'Shorts', '#'),
(140, 7, 'Shorts', '#'),
(140, 8, 'Shorts', '#'),
(141, 2, 'Trousers', '#'),
(141, 3, 'Trousers', '#'),
(141, 4, 'Trousers', '#'),
(141, 5, 'Trousers', '#'),
(141, 6, 'Trousers', '#'),
(141, 7, 'Trousers', '#'),
(141, 8, 'Trousers', '#'),
(142, 2, 'Sweatshirts', '#'),
(142, 3, 'Sweatshirts', '#'),
(142, 4, 'Sweatshirts', '#'),
(142, 5, 'Sweatshirts', '#'),
(142, 6, 'Sweatshirts', '#'),
(142, 7, 'Sweatshirts', '#'),
(142, 8, 'Sweatshirts', '#');
";
