<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVe2yd8g\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVe2yd8g/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVe2yd8g.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVe2yd8g\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVe2yd8g\appDevDebugProjectContainer([
    'container.build_hash' => 'Ve2yd8g',
    'container.build_id' => '21afb2c3',
    'container.build_time' => 1570008854,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVe2yd8g');
