<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0jqpfkj\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0jqpfkj/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0jqpfkj.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0jqpfkj\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0jqpfkj\appDevDebugProjectContainer([
    'container.build_hash' => '0jqpfkj',
    'container.build_id' => '9af95b92',
    'container.build_time' => 1570507385,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0jqpfkj');
